name: Start Runner
  
on:
  workflow_call:
    outputs:
      runner:
        description: "The runner output string"
        value: ${{ jobs.startrunner.outputs.runner }}
      
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
          
jobs:
  startrunner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.readid.outputs.runner }}
      runnerflag: ${{ steps.readid.outputs.flag }}
    steps:
      - uses: actions/checkout@v3
      - name: test
        id: readid
        run: |
           aws s3 cp s3://instance-id/instanceid.txt ${{ github.workspace }}/id.txt --region us-west-1
           input='${{ github.workspace }}/InstanceID.txt'
           sed 's/\r$//' ${{ github.workspace }}/id.txt > input.txt
           echo "" >> input.txt
           while IFS="\n" read -r line
           do 
             status=$(aws ec2 describe-instance-status --region us-west-1 --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
             if [ "$status" != "running" ];then
               aws ec2 start-instances --instance-ids $line
               echo "::set-output name=runner::$line"
               echo "::set-output name=flag::true"
               break
             fi
             echo "::set-output name=flag::false"
           done < input
