name: Build
on: 
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          
jobs:
  startrunner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test 
        id: readid
        run: |
             aws ec2 describe-instance-status --region us-west-1 --instance-id i-03df3b51363d40fb6
