# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on: 
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          
jobs:
  startrunner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.readid.outputs.runner }}
      runnerflag: ${{ steps.readid.outputs.flag }}
    steps:
      - uses: actions/checkout@v3
      - name: test
        id: readid
        #continue-on-error: true 
        run: |
           aws s3 cp s3://jeena-aws-s3/Instance-details/instanceid.txt ${{ github.workspace }}/id.txt
           cat ${{ github.workspace }}/id.txt
           input='${{ github.workspace }}/id.txt'
           while IFS= read -r line
           do
             echo $line | sed 's/^ *//g'
             status=$(aws ec2 describe-instance-status --region ${{ secrets.AWS_REGION }} --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
             if [ "$status" != "running" ];then
               aws ec2 start-instances --instance-ids $line
               echo "::set-output name=runner::$line"
               echo "::set-output name=flag::true"
               break
             fi
             echo "::set-output name=flag::false"
           done < "$input"
           
#   build:
#      needs: startrunner
#      runs-on: self-hosted
#      steps:
#         - run: |
#            echo "Hello World"
#            sleep 240
           
#   stop_runner:
#     needs: [ startrunner]
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           aws ec2 stop-instances --instance-ids ${{ needs.startrunner.outputs.runner }}
        
   
         


         
         
             
   
           
  
      
  
    
