name: Build
on: 
  workflow_dispatch:
env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  Pre-Release:
    name: Pre-Release
    uses: ./.github/workflows/pre-release.yml
    
  initializerunner:
    name: Intialize Runner
    needs: Pre-Release
    uses: ./.github/workflows/action.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
  build:
     needs: [initializerunner,Pre-Release]
     runs-on: ${{ needs.initializerunner.outputs.activerunner }}
     steps:
        - run: |
           echo "Hello World"
           
  Sonar:
    needs: [build,initializerunner]
    runs-on: ${{ needs.initializerunner.outputs.activerunner }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Malavika1113_Demo-Github-Migration -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
 
  Fortify:
    needs: [initializerunner,Pre-Release]
    runs-on: ubuntu-latest
    steps:    
      - name: Fortify Analysis
        run: echo Starting Fortify stage!!
        
  Post-Release:
    name: Post-Release
    needs: [initializerunner,Pre-Release,build,Sonar,Fortify]
    uses: ./.github/workflows/post-release.yml  
      
  Declarative-Post-Actions:
    needs: [Post-Release]
    runs-on: ubuntu-latest
    steps:    
      - name: Sent Results
        run: echo Mailing results to recipients!!     
        
  stop_runner:
    needs: [initializerunner,build,Sonar,Declarative-Post-Actions]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.initializerunner.outputs.activerunner }}
          aws ec2 stop-instances --instance-ids ${{ needs.initializerunner.outputs.activerunner }} --region us-west-1
          
