name: Build
on: 
  workflow_dispatch:
          
jobs:
  initializerunner:
    runs-on: ubuntu-latest
    name: Intialize Runner
    steps:
      - uses: ./.github/workflows/startRunner.yml
           
  build:
     needs: initializerunner
     runs-on: ${{ needs.initializerunner.outputs.runner }}
     steps:
        - run: |
           echo "Hello World"
           sleep 240
           
  stop_runner:
    needs: [ initializerunner]
    runs-on: ubuntu-latest
    steps:
      - run: |
          aws ec2 stop-instances --instance-ids ${{ needs.initializerunner.outputs.runner }}
        
   
         


         
         
             
   
           
  
      
  
    
