name: Build
on: 
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}          
jobs:
  initializerunner:
    name: Intialize Runner
    uses: ./.github/workflows/action.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      
            
  build:
     needs: initializerunner
     runs-on: ${{ needs.initializerunner.outputs.runner }}
     steps:
        - run: |
           echo "Hello World"
           sleep 60
           
  stop_runner:
    needs: [ build, initializerunner]
    runs-on: ubuntu-latest
    steps:
      - run: |
          aws ec2 stop-instances --instance-ids ${{ needs.initializerunner.outputs.runner }}
