name: Build
on: 
  workflow_dispatch:
          
jobs:
  initializerunner:
    runs-on: ubuntu-latest
    name: Intialize Runner
    steps:
      - uses: ./.github/workflows/startRunner.yml
           
#   build:
#      needs: startrunner
#      runs-on: self-hosted
#      steps:
#         - run: |
#            echo "Hello World"
#            sleep 240
           
#   stop_runner:
#     needs: [ startrunner]
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           aws ec2 stop-instances --instance-ids ${{ needs.startrunner.outputs.runner }}
        
   
         


         
         
             
   
           
  
      
  
    
