# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on: 
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          
jobs:
  startrunner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.readid.outputs.runner }}
      runnerflag: ${{ steps.readid.outputs.flag }}
    steps:
      - uses: actions/checkout@v3
      - name: test
        id: readid
        continue-on-error: true 
        run: |
           input='${{ github.workspace }}/InstanceID.txt'
           while IFS= read -r line
           do
             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
             if [ "$status" != "running" ];then
               aws ec2 start-instances --instance-ids $line
               echo "::set-output name=runner::$line"
               echo "::set-output name=flag::true"
               break
             fi
             echo "::set-output name=flag::false"
           done < "$input"
           #sleep 60
           exit1
           
      - name: retry
        continue-on-error: true
        id: retry1
        if: steps.test.outcome=='failure'  
        run: |
          input='${{ github.workspace }}/InstanceID.txt'
           while IFS= read -r line
           do
             echo "$line"
             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
             if [ "$status" != "running" ];then
               aws ec2 start-instances --instance-ids $line
               echo "::set-output name=runner::$line"
               echo "::set-output name=flag::true"
               break
             else
               echo "::set-output name=flag::false"
             fi
           done < "$input"
           sleep 60
           if [ "$flag" == "false" ];then
             exit 1
           fi
           
      - name: retry 2
        continue-on-error: true
        id: retry2
        if: steps.retry1.outcome=='failure'   # check the step outcome, retry 2nd time
        run: |
          echo retry 2nd time
          input='${{ github.workspace }}/InstanceID.txt'
           while IFS= read -r line
           do
             echo "$line"
             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
             if [ "$status" != "running" ];then
               aws ec2 start-instances --instance-ids $line
               echo "::set-output name=runner::$line"
               echo "::set-output name=flag::true"
               break
           else
             echo "::set-output name=flag::false"
           fi
           done < "$input"
           sleep 60
           if [ "$flag" == "false" ];then
             exit 1
           fi
           
      - name: retry 3
        continue-on-error: true
        id: retry3
        if: steps.retry2.outcome=='failure'      # check the step outcome, retry 3rd time
        run: |
          echo retry 3rd time
          input='${{ github.workspace }}/InstanceID.txt'
           while IFS= read -r line
           do
             echo "$line"
             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
             if [ "$status" != "running" ];then
               aws ec2 start-instances --instance-ids $line
               echo "::set-output name=runner::$line"
               echo "::set-output name=flag::true"
               break
             else
               echo "::set-output name=flag::false"
             fi
           done < "$input"
           sleep 60
           if [ "$flag" == "false" ];then
             exit 1
           fi
           
      - name: set the status    
        if: always()
        run: |
          echo ${{ steps.test.outcome }} ${{ steps.retry1.outcome }} ${{ steps.retry2.outcome }}  ${{ steps.retry3.outcome}}
          if ${{ steps.test.outcome=='success' || steps.retry1.outcome=='success' || steps.retry2.outcome=='success' || steps.retry3.outcome=='success' }}; then
             echo "Proceed to next job"
          else
             exit 1
          fi
    
  build:
     needs: startrunner
     runs-on: self-hosted
     steps:
        - run: |
           echo "Hello World"
           sleep 240
           
  stop_runner:
    needs: [build, startrunner]
    runs-on: ubuntu-latest
    steps:
      - run: |
          aws ec2 stop-instances --instance-ids ${{ needs.startrunner.outputs.runner }}
        
   
         


         
         
             
   
           
  
      
  
    
