name: SONAR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Sonar:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Sonar Analysis
          run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Malavika1113_Demo-Github-Migration -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
